import { Link } from "react-router-dom"
import { ArrowRight, Check } from "lucide-react"

import { SiteFooter, SiteNav } from "@/components/site/SitePage"
import { Badge } from "@/components/ui/badge"

const FREE_FEATURES = [
  "Personalized roadmap generated by AI",
  "Prerequisite aware skill graph",
  "AI assistant with full context of your path",
  "Progress tracking across all milestones",
  "Access to all 92+ role tracks",
]

const PRO_FEATURES = [
  "Team workspaces and shared roadmaps",
  "Institution dashboards and cohort analytics",
  "Priority AI with faster generation",
  "Custom tracks for your curriculum",
]

export default function Pricing() {
  return (
    <div className="min-h-screen bg-background">
      <SiteNav />
      <main className="mx-auto w-full max-w-5xl px-6 py-14">
        <h1 className="font-display text-4xl font-semibold tracking-tight text-ink-primary md:text-5xl">
          Simple pricing that starts at zero
        </h1>
        <p className="mt-5 max-w-2xl text-lg leading-relaxed text-ink-secondary">
          Coursegram is free to use today. Every core feature, from personalized roadmaps to the AI
          assistant, is available to every learner. A Pro plan is on the way for teams and
          institutions, but learners will always have a generous free tier.
        </p>

        <div className="mt-12 grid gap-6 md:grid-cols-2">
          <div className="flex flex-col rounded-2xl border border-accent-600 bg-surface p-8 shadow-sm">
            <p className="text-sm font-semibold text-ink-primary">Free</p>
            <div className="mt-3 flex items-baseline gap-2">
              <span className="font-display text-4xl font-semibold tracking-tight text-ink-primary">$0</span>
              <span className="text-sm text-ink-secondary">forever</span>
            </div>
            <p className="mt-3 text-sm leading-relaxed text-ink-secondary">
              Everything you need to go from a vague goal to a clear, adaptive learning path.
            </p>
            <ul className="mt-6 flex-1 space-y-3">
              {FREE_FEATURES.map((feature) => (
                <li key={feature} className="flex items-start gap-2.5 text-sm text-ink-secondary">
                  <Check className="mt-0.5 h-4 w-4 shrink-0 text-accent-600" />
                  {feature}
                </li>
              ))}
            </ul>
            <Link
              to="/login"
              className="mt-8 inline-flex items-center justify-center gap-2 rounded-lg bg-accent-700 px-5 py-3 text-sm font-semibold text-surface transition-colors hover:bg-accent-600"
            >
              Get Started Free
              <ArrowRight className="h-4 w-4" />
            </Link>
          </div>

          <div className="relative flex flex-col rounded-2xl border border-border bg-surface/70 p-8">
            <span className="absolute right-6 top-6">
              <Badge variant="accent">Coming soon</Badge>
            </span>
            <p className="text-sm font-semibold text-ink-primary">Pro</p>
            <div className="mt-3">
              <span className="font-display text-4xl font-semibold tracking-tight text-ink-muted">
                For teams
              </span>
            </div>
            <p className="mt-3 text-sm leading-relaxed text-ink-secondary">
              Built for bootcamps, training teams, and institutions that guide many learners at once.
            </p>
            <ul className="mt-6 flex-1 space-y-3">
              {PRO_FEATURES.map((feature) => (
                <li key={feature} className="flex items-start gap-2.5 text-sm text-ink-secondary">
                  <Check className="mt-0.5 h-4 w-4 shrink-0 text-ink-muted" />
                  {feature}
                </li>
              ))}
            </ul>
            <Link
              to="/institutions"
              className="mt-8 inline-flex items-center justify-center gap-2 rounded-lg border border-border px-5 py-3 text-sm font-semibold text-ink-primary transition-colors hover:bg-accent-50"
            >
              Talk to us about Pro
              <ArrowRight className="h-4 w-4" />
            </Link>
          </div>
        </div>

        <div className="mt-14 rounded-2xl border border-border bg-surface p-8">
          <h2 className="font-display text-xl font-semibold tracking-tight text-ink-primary">
            Why free?
          </h2>
          <p className="mt-3 max-w-3xl text-sm leading-relaxed text-ink-secondary">
            We believe the biggest barrier to learning is not money, it is direction. Most people who
            want to change careers already know how to find videos and articles. What they lack is an
            ordered plan that fits their life. By keeping the roadmap engine free, we remove that
            barrier for as many learners as possible while institutions pay for the coordination and
            analytics tools they need.
          </p>
        </div>
      </main>
      <SiteFooter />
    </div>
  )
}
