import { Link } from "react-router-dom"
import { ArrowRight, GraduationCap, GitBranch, MapPinned, RefreshCw } from "lucide-react"

import { SiteFooter, SiteNav } from "@/components/site/SitePage"

const SAMPLE_PHASES = [
  {
    phase: "Phase 1",
    title: "Foundations",
    milestone: "Milestone: Build your first interactive web page",
    topics: ["HTML structure and semantics", "CSS layout with flexbox", "JavaScript basics", "Git and GitHub workflow"],
  },
  {
    phase: "Phase 2",
    title: "Core Skills",
    milestone: "Milestone: Ship a complete React application",
    topics: ["React components and props", "State management patterns", "Fetching data from APIs", "Testing fundamentals"],
  },
  {
    phase: "Phase 3",
    title: "Specialization",
    milestone: "Milestone: Deploy a production ready portfolio project",
    topics: ["Performance optimization", "Authentication flows", "TypeScript in practice", "Deployment and CI"],
  },
]

export default function RoadmapPage() {
  return (
    <div className="min-h-screen bg-background">
      <SiteNav />
      <main className="mx-auto w-full max-w-5xl px-6 py-14">
        <h1 className="max-w-2xl font-display text-4xl font-semibold tracking-tight text-ink-primary md:text-5xl">
          What is a Coursegram roadmap?
        </h1>
        <p className="mt-5 max-w-2xl text-lg leading-relaxed text-ink-secondary">
          A roadmap is your personalized learning path, generated by AI and structured the way real
          careers are built. Instead of a flat list of courses, it organizes everything you need to
          learn into ordered phases, each ending in a concrete milestone. You always know what to
          learn now, why it matters, and what unlocks next.
        </p>

        <div className="mt-12 grid gap-6 md:grid-cols-2">
          <div className="rounded-xl border border-border bg-surface p-6">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent-50 text-accent-600">
              <MapPinned className="h-4 w-4" />
            </div>
            <p className="mt-4 text-sm font-semibold text-ink-primary">Phases with milestones</p>
            <p className="mt-2 text-sm leading-relaxed text-ink-secondary">
              Each roadmap is divided into phases like foundations, core skills, and specialization.
              Every phase closes with a measurable milestone such as shipping a working project or
              passing an assessment, so progress is proven rather than assumed.
            </p>
          </div>
          <div className="rounded-xl border border-border bg-surface p-6">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent-50 text-accent-600">
              <GitBranch className="h-4 w-4" />
            </div>
            <p className="mt-4 text-sm font-semibold text-ink-primary">Prerequisite aware skill graph</p>
            <p className="mt-2 text-sm leading-relaxed text-ink-secondary">
              Topics are not listed at random. Coursegram models skills as a graph where each topic
              depends on the ones before it. If you want to learn Redux, the graph makes sure state
              management in React comes first. This prevents the classic trap of jumping into
              advanced material before the basics hold.
            </p>
          </div>
          <div className="rounded-xl border border-border bg-surface p-6">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent-50 text-accent-600">
              <GraduationCap className="h-4 w-4" />
            </div>
            <p className="mt-4 text-sm font-semibold text-ink-primary">92+ tracks from roadmap.sh reference data</p>
            <p className="mt-2 text-sm leading-relaxed text-ink-secondary">
              Your goal can be anything from frontend developer to DevOps engineer to data analyst.
              Coursegram draws on reference data from over 92 established roadmap.sh role tracks,
              covering the skills, tools, and order of study that practitioners actually recommend.
            </p>
          </div>
          <div className="rounded-xl border border-border bg-surface p-6">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent-50 text-accent-600">
              <RefreshCw className="h-4 w-4" />
            </div>
            <p className="mt-4 text-sm font-semibold text-ink-primary">Adaptive regeneration</p>
            <p className="mt-2 text-sm leading-relaxed text-ink-secondary">
              Plans change and that is fine. As you complete assessments, skip ahead, or tell the AI
              assistant your priorities shifted, the remaining roadmap regenerates around reality.
              Completed work is respected, gaps are re-prioritized, and the finish line moves with
              you instead of against you.
            </p>
          </div>
        </div>

        <h2 className="mt-14 font-display text-2xl font-semibold tracking-tight text-ink-primary">
          A roadmap, at a glance
        </h2>
        <p className="mt-2 max-w-2xl text-sm leading-relaxed text-ink-secondary">
          Here is how a frontend developer roadmap typically breaks down across three phases.
        </p>
        <div className="mt-6 grid gap-6 md:grid-cols-3">
          {SAMPLE_PHASES.map((phase) => (
            <div key={phase.phase} className="rounded-xl border border-border bg-surface p-6">
              <span className="inline-flex rounded-full bg-accent-50 px-3 py-1 text-xs font-semibold text-accent-700">
                {phase.phase}
              </span>
              <p className="mt-3 text-base font-semibold text-ink-primary">{phase.title}</p>
              <p className="mt-1 text-xs font-medium text-accent-700">{phase.milestone}</p>
              <ul className="mt-4 space-y-2">
                {phase.topics.map((topic) => (
                  <li key={topic} className="text-sm leading-relaxed text-ink-secondary">
                    {topic}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        <div className="mt-14 rounded-2xl border border-border bg-surface p-8 text-center">
          <h2 className="font-display text-xl font-semibold tracking-tight text-ink-primary">
            Generate yours in minutes
          </h2>
          <p className="mx-auto mt-2 max-w-md text-sm text-ink-secondary">
            Describe your goal, take a short quiz, and get a roadmap tailored to you.
          </p>
          <Link
            to="/login"
            className="mt-5 inline-flex items-center gap-2 rounded-lg bg-accent-700 px-5 py-2.5 text-sm font-semibold text-surface transition-colors hover:bg-accent-600"
          >
            Get Started Free
            <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      </main>
      <SiteFooter />
    </div>
  )
}

