"""Per track skill categories, generated by the LLM and cached on disk.

The frontend used to map every track onto the same fixed keyword categories
(frontend, backend, database), which produced meaningless groupings for
tracks like devops. Categories are now derived from each track's real topic
list once and cached under data/runtime/category_cache.
"""

import json
import os
import re

from app import llm
from app.roadmap_store import RoadmapNotFound, load_roadmap_topics

CACHE_DIR = os.path.join(os.path.dirname(__file__), "data", "runtime", "category_cache")

MAX_TOPICS_IN_PROMPT = 80


class CategoryError(Exception):
    pass


def _cache_path(slug: str) -> str:
    return os.path.join(CACHE_DIR, f"{slug}.json")


def _valid_categories(payload) -> list[dict] | None:
    if not isinstance(payload, dict):
        return None
    categories = payload.get("categories")
    if not isinstance(categories, list) or not categories:
        return None
    cleaned: list[dict] = []
    seen: set[str] = set()
    for item in categories:
        if not isinstance(item, dict):
            continue
        name = str(item.get("name", "")).strip()
        topics = item.get("topics")
        if not name or not isinstance(topics, list) or not topics:
            continue
        topics = [str(topic).strip() for topic in topics if str(topic).strip()]
        if not topics:
            continue
        cleaned.append({"name": name, "topics": topics})
        seen.update(topic.lower() for topic in topics)
    return cleaned or None


def _fallback_categories(topics: list[str]) -> list[dict]:
    """Split topics into sequential bands when the LLM is unavailable."""
    size = max(4, min(12, len(topics) // 4 or 4))
    categories = []
    for index in range(0, len(topics), size):
        band = topics[index : index + size]
        categories.append({"name": f"Part {index // size + 1}", "topics": band})
    return categories


def get_categories(slug: str) -> dict:
    """Return meaningful skill categories for a track, cached after first run."""
    try:
        topics = load_roadmap_topics(slug)
    except RoadmapNotFound:
        raise RoadmapNotFound(slug)

    cache = _cache_path(slug)
    if os.path.exists(cache):
        try:
            with open(cache, "r", encoding="utf-8") as file:
                payload = json.load(file)
            categories = _valid_categories(payload)
            if categories is not None:
                return {"slug": slug, "categories": categories}
        except (OSError, json.JSONDecodeError):
            pass

    if not llm.is_configured():
        categories = _fallback_categories(topics)
    else:
        sample = topics[:MAX_TOPICS_IN_PROMPT]
        prompt = (
            f"Group these {slug} learning topics into 4 to 8 meaningful skill "
            "categories named after real skill areas of the track, for example "
            "for devops: Linux, Cloud Providers, Containers, CI/CD. Every topic "
            "must appear in exactly one category. Use the given topic strings "
            "verbatim. Respond with JSON only: "
            '{"categories": [{"name": "...", "topics": ["...", "..."]}]}.\n'
            "Topics: " + "; ".join(sample)
        )
        try:
            raw = llm.chat_completion(
                [{"role": "user", "content": prompt}],
                json_mode=True,
                temperature=0.2,
            )
            categories = _valid_categories(json.loads(raw))
        except (llm.LLMError, ValueError):
            categories = None
        if categories is None:
            categories = _fallback_categories(topics)

    os.makedirs(CACHE_DIR, exist_ok=True)
    with open(cache, "w", encoding="utf-8") as file:
        json.dump({"slug": slug, "categories": categories}, file, ensure_ascii=False, indent=2)
    return {"slug": slug, "categories": categories}
