"""First time onboarding: placement quiz generation and grading.

Quiz questions are generated by the configured LLM provider from the
track's topic list and what the learner says they already know. Grading
is deterministic and local so scores never depend on an LLM being
available. When no LLM key is configured the quiz endpoints return 503
and the frontend skips straight to the roadmap.
"""

import difflib
import json
import logging
import re
from datetime import datetime, timezone

from fastapi import HTTPException
from pydantic import BaseModel, Field

from app import llm
from app.roadmap_store import (
    RoadmapNotFound,
    enforce_phase_order,
    list_roadmap_options,
    load_roadmap_topics,
)

logger = logging.getLogger("app.onboarding")

QUIZ_QUESTION_COUNT = 4


class GoalRequest(BaseModel):
    goal_text: str = Field(min_length=3, max_length=2000, description="Free text learning goal")


class GoalArea(BaseModel):
    name: str
    topics: list[str]


class GoalAnalysisResponse(BaseModel):
    track_slug: str
    summary: str
    areas: list[GoalArea]


class PlanRequest(BaseModel):
    slug: str
    goal_text: str = ""
    area_levels: dict[str, str] = Field(default_factory=dict)
    known_topics: list[str] = Field(default_factory=list)
    weekly_hours: int | None = Field(default=None, ge=1, le=80)


class PlanPhase(BaseModel):
    name: str
    milestone: str
    topics: list[str]


class PlanResponse(BaseModel):
    slug: str
    summary: str
    phases: list[PlanPhase]


class QuizRequest(BaseModel):
    slug: str
    known_topics: list[str] = Field(default_factory=list)
    skill_level: str = "beginner"


class QuizQuestion(BaseModel):
    id: str
    question: str
    options: list[str]
    answer_index: int
    topic: str


class QuizResponse(BaseModel):
    slug: str
    questions: list[QuizQuestion]


class GradeRequest(BaseModel):
    questions: list[QuizQuestion]
    answers: list[int] = Field(description="Selected option index per question, -1 when skipped")


class GradeResponse(BaseModel):
    score: int
    total: int
    recommended_level: str
    summary: str


def _parse_json(raw: str) -> dict:
    """Parse an LLM JSON reply, tolerating prose or fences around the object."""
    cleaned = raw.strip()
    fence = re.match(r"^```(?:json)?\s*(.*?)\s*```$", cleaned, re.DOTALL)
    if fence:
        cleaned = fence.group(1).strip()
    try:
        data = json.loads(cleaned)
    except ValueError:
        start = cleaned.find("{")
        end = cleaned.rfind("}")
        if start == -1 or end <= start:
            logger.warning("LLM reply contained no JSON object: %.300s", raw)
            raise HTTPException(status_code=502, detail="LLM reply contained no JSON object")
        try:
            data = json.loads(cleaned[start : end + 1])
        except ValueError as error:
            logger.warning("LLM returned invalid JSON (%s): %.300s", error, raw)
            raise HTTPException(status_code=502, detail=f"LLM returned invalid JSON: {error}")
    if not isinstance(data, dict):
        raise HTTPException(status_code=502, detail="LLM returned unexpected JSON shape")
    return data


def _canonical_topic(topic: str, remaining: list[str]) -> str | None:
    """Map an LLM topic string onto the track reference list.

    Tolerates small wording drift so a near miss does not get dropped:
    the roadmap, progress tracking, and resource matching all assume
    phases use the reference topic names verbatim.
    """
    remaining_lower = [name.lower() for name in remaining]
    lower = topic.strip().lower()
    if lower in remaining_lower:
        return remaining[remaining_lower.index(lower)]
    close = difflib.get_close_matches(lower, remaining_lower, n=1, cutoff=0.82)
    if close:
        return remaining[remaining_lower.index(close[0])]
    return None


def resolve_track(candidate: str, goal_text: str, options: list[dict]) -> str | None:
    """Resolve an LLM track pick onto a real slug, fuzzily.

    The model rarely echoes slugs verbatim ("full stack developer" vs
    "full-stack"), so try normalized and near matches, then match the
    goal's own words against slugs and titles before giving up.
    """
    slugs = [option["slug"] for option in options]
    candidate_clean = candidate.strip().lower()
    if candidate_clean in slugs:
        return candidate_clean
    normalized = re.sub(r"[\s_]+", "-", candidate_clean)
    if normalized in slugs:
        return normalized
    close = difflib.get_close_matches(normalized, slugs, n=1, cutoff=0.75)
    if close:
        return close[0]
    goal_lower = goal_text.lower()
    for option in options:
        title_words = re.findall(r"[a-z0-9]+", option["title"].lower())
        if len(title_words) >= 2 and all(f" {word}" in f" {goal_lower}" for word in title_words):
            return option["slug"]
    for option in options:
        slug_words = [word for word in option["slug"].split("-") if word]
        if len(slug_words) >= 2 and all(f" {word}" in f" {goal_lower}" for word in slug_words):
            return option["slug"]
    return None


async def generate_custom_track(goal_text: str) -> dict:
    """Fallback when no existing track fits: design a new LearningGraph."""
    prompt = (
        "You design learning tracks for Coursegram as skill graphs. No "
        "existing track matches the learner's goal, so design a new one. "
        "Create 12 to 18 topics that take a learner from fundamentals to "
        "job ready for this goal, ordered so every topic only depends on "
        "earlier ones. Respond with JSON only: {\"slug\": \"kebab-case-"
        "slug\", \"title\": \"Track Title\", \"nodes\": [{\"id\": "
        "\"kebab-id\", \"name\": \"Topic Name\", \"prerequisites\": "
        "[\"ids of earlier topics\"]}]}\n"
        f"Learner goal: {goal_text}"
    )
    raw = await llm.chat_completion(
        [{"role": "user", "content": prompt}],
        json_mode=True,
        temperature=0.4,
        max_tokens=3000,
    )
    data = _parse_json(raw)
    slug = re.sub(r"[^a-z0-9]+", "-", str(data.get("slug", "")).lower()).strip("-")
    title = str(data.get("title", "")).strip()
    nodes = data.get("nodes")
    if not slug or not title or not isinstance(nodes, list) or len(nodes) < 8:
        raise HTTPException(status_code=502, detail="The generated track was unusable")
    slug = slug[:60]
    from app.roadmap_store import _normalize_graph, insert_generated_track

    normalized = _normalize_graph(slug, {"slug": slug, "title": title, "nodes": nodes})
    insert_generated_track(slug, title, normalized)
    return {"slug": slug, "title": title, "custom": True}


async def analyze_goal(payload: GoalRequest) -> GoalAnalysisResponse:
    """Parse a free text goal into a track and major skill areas."""
    if not llm.is_configured():
        raise HTTPException(status_code=503, detail="LLM is not configured on the server")

    options = list_roadmap_options()
    prompt = (
        "You are the Coursegram onboarding assistant. A learner describes "
        "their goal in natural language. Pick the best matching track from "
        "the available tracks and identify the 3 to 6 major skill areas of "
        "that track the learner must master. track_slug MUST be copied "
        "verbatim from the list below. Respond with JSON only: "
        '{"track_slug": "...", "summary": "one sentence confirming the goal", '
        '"areas": [{"name": "...", "topics": ["..."]}]} where area topics are '
        "short skill names, not full courses.\n"
        f"Available tracks (slug: title):\n"
        + "\n".join(f"- {option['slug']}: {option['title']}" for option in options)
        + f"\n\nLearner goal: {payload.goal_text}"
    )
    raw = await llm.chat_completion(
        [{"role": "user", "content": prompt}],
        json_mode=True,
        temperature=0.2,
    )
    data = _parse_json(raw)
    track_slug = resolve_track(
        str(data.get("track_slug", "")), payload.goal_text, options
    )
    custom_note = ""
    if track_slug is None:
        generated = await generate_custom_track(payload.goal_text)
        track_slug = generated["slug"]
        custom_note = "We designed a custom track for this goal. "
    areas = [
        GoalArea(name=str(item.get("name", "")).strip(), topics=[str(t) for t in item.get("topics", [])])
        for item in data.get("areas", [])
        if isinstance(item, dict) and item.get("name")
    ]
    if not areas:
        raise HTTPException(status_code=502, detail="The assistant could not identify skill areas")
    summary = custom_note + str(data.get("summary", "")).strip()
    return GoalAnalysisResponse(
        track_slug=track_slug,
        summary=summary,
        areas=areas,
    )


async def generate_plan(payload: PlanRequest) -> PlanResponse:
    """Generate a personalized roadmap from the track reference data."""
    if not llm.is_configured():
        raise HTTPException(status_code=503, detail="LLM is not configured on the server")

    try:
        from app.roadmap_store import load_roadmap_graph

        graph = load_roadmap_graph(payload.slug)
        topics = [n["name"] for n in graph["nodes"]]
        choice_groups = graph.get("choice_groups", [])
    except RoadmapNotFound:
        raise HTTPException(status_code=404, detail="Unknown roadmap slug")

    known = set(topic.lower() for topic in payload.known_topics)
    remaining = [t for t in topics if t.lower() not in known]
    ref_list = "; ".join(remaining[:80])
    if len(remaining) > 80:
        ref_list += f"; ... and {len(remaining) - 80} more"
    levels = ", ".join(f"{area}: {level}" for area, level in payload.area_levels.items()) or "unknown"
    goal = payload.goal_text or f"master {payload.slug}"
    pace_hint = (
        f"The learner can study about {payload.weekly_hours} hours per week; "
        "size the phases realistically for that pace and mention it in the summary. "
        if payload.weekly_hours
        else ""
    )
    choice_hint = ""
    if choice_groups:
        id_to_name = {n["id"]: n["name"] for n in graph["nodes"]}
        parts = []
        for grp in choice_groups:
            names = [id_to_name.get(o, o) for o in grp.get("options", [])]
            parts.append(f"{grp.get('prompt', 'Pick one')} -> {', '.join(names)} (choose ONE only)")
        choice_hint = "Choice groups (pick exactly one per group, never list multiple):\n" + "\n".join(parts) + "\n"

    prompt = (
        "You are the Coursegram path generator. Build a personalized "
        f"learning roadmap for a learner whose goal is: {goal}. "
        f"Track: {payload.slug}. Self rated proficiency per skill area: {levels}. "
        + pace_hint
        + f"Topics the learner already knows (skip these): "
        f"{', '.join(payload.known_topics) if payload.known_topics else 'none'}.\n"
        + choice_hint
        + "Use this ordered reference topic list from the track as the source of "
        "truth, taking topics verbatim where possible:\n"
        f"{ref_list}\n\n"
        "Produce 3 to 5 sequential phases. Each phase has a short name, one "
        "concrete milestone the learner can demonstrate, and its topics taken "
        "from the reference list. For choice groups, include at most ONE option "
        "per group. If the learner rated an area intermediate or advanced, "
        "start that area at the next difficulty tier. Every topic must be verbatim "
        "from the reference list. Respond with JSON only: "
        '{"summary": "one sentence describing the path", "phases": '
        '[{"name": "...", "milestone": "...", "topics": ["..."]}]}'
    )

    name_to_id = {n["name"].lower(): n["id"] for n in graph["nodes"]}
    opt_to_group = {opt: grp["id"] for grp in choice_groups for opt in grp.get("options", [])}

    def build_response(data: dict) -> PlanResponse:
        phases = [
            PlanPhase(
                name=str(item.get("name", "")).strip(),
                milestone=str(item.get("milestone", "")).strip(),
                topics=[str(topic) for topic in item.get("topics", []) if str(topic).strip()],
            )
            for item in data.get("phases", [])
            if isinstance(item, dict) and item.get("name")
        ]
        if not phases:
            raise ValueError("no phases in reply")
        seen_group: dict[str, str] = {}
        filtered: list[PlanPhase] = []
        for phase in phases:
            kept: list[str] = []
            for topic in phase.topics:
                canonical = _canonical_topic(topic, remaining)
                if canonical is None:
                    continue
                tid = name_to_id.get(canonical.lower())
                grp = opt_to_group.get(tid or "")
                if grp and grp in seen_group:
                    continue
                if grp:
                    seen_group[grp] = canonical
                if canonical not in kept:
                    kept.append(canonical)
            if kept:
                filtered.append(PlanPhase(name=phase.name, milestone=phase.milestone, topics=kept))
        if not filtered:
            raise ValueError("every phase topic was dropped")
        ordered = enforce_phase_order(graph, [phase.model_dump() for phase in filtered])
        filtered = [PlanPhase(**phase) for phase in ordered]
        return PlanResponse(
            slug=payload.slug,
            summary=str(data.get("summary", "")).strip(),
            phases=filtered,
        )

    last_error: str | None = None
    for attempt in range(2):
        attempt_prompt = prompt
        if attempt > 0:
            attempt_prompt += (
                "\n\nImportant: reply with the raw JSON object only. "
                "No markdown, no commentary, no truncated output."
            )
        try:
            raw = await llm.chat_completion(
                [{"role": "user", "content": attempt_prompt}],
                json_mode=True,
                temperature=0.3 if attempt == 0 else 0.5,
                max_tokens=4096,
            )
            result = build_response(_parse_json(raw))
            return result
        except llm.LLMError as error:
            last_error = str(error)
            logger.warning("Plan attempt %s failed: %s", attempt + 1, error)
        except (HTTPException, ValueError) as error:
            detail = error.detail if isinstance(error, HTTPException) else str(error)
            last_error = str(detail)
            logger.warning("Plan attempt %s failed: %s", attempt + 1, detail)
    raise HTTPException(status_code=502, detail="The assistant could not build a roadmap")


async def generate_quiz(payload: QuizRequest) -> QuizResponse:
    """Ask the LLM for placement questions on the track's topics."""
    try:
        topics = load_roadmap_topics(payload.slug)
    except RoadmapNotFound:
        raise HTTPException(status_code=404, detail="Unknown roadmap slug")

    if not llm.is_configured():
        raise HTTPException(status_code=503, detail="LLM is not configured on the server")

    known = ", ".join(payload.known_topics) if payload.known_topics else "nothing yet"
    prompt = (
        "You build placement quizzes for software learners. "
        f"Track: {payload.slug}. Self reported level: {payload.skill_level}. "
        f"Topics the learner already knows: {known}. "
        "Create a multiple choice quiz that checks real understanding of the "
        "earliest and most fundamental topics of this track, weighted toward "
        "prerequisite knowledge. "
        f"Return exactly {QUIZ_QUESTION_COUNT} questions. "
        "Respond with JSON only using this shape: "
        '{"questions": [{"id": "q1", "question": "...", '
        '"options": ["...", "...", "...", "..."], "answer_index": 0, '
        '"topic": "..."}]}. '
        "Do not include any text outside the JSON."
    )
    raw = await llm.chat_completion(
        [{"role": "user", "content": prompt}],
        json_mode=True,
        temperature=0.6,
    )
    data = _parse_json(raw)
    questions = [QuizQuestion(**item) for item in data.get("questions", [])]
    if not questions:
        raise HTTPException(status_code=502, detail="Quiz generation returned no questions")
    return QuizResponse(slug=payload.slug, questions=questions[:QUIZ_QUESTION_COUNT])


def grade_quiz(payload: GradeRequest) -> GradeResponse:
    """Score the quiz locally and map the result to a skill level."""
    total = len(payload.questions)
    if total == 0 or len(payload.answers) != total:
        raise HTTPException(status_code=422, detail="Answers must match questions")

    score = 0
    missed: list[str] = []
    for question, answer in zip(payload.questions, payload.answers):
        if 0 <= answer == question.answer_index:
            score += 1
        else:
            missed.append(question.topic or question.id)

    ratio = score / total
    if ratio >= 0.8:
        level = "advanced"
    elif ratio >= 0.5:
        level = "intermediate"
    else:
        level = "beginner"

    if missed:
        summary = "Focus areas: " + ", ".join(sorted(set(missed))[:4]) + "."
    else:
        summary = "Strong across all quiz topics."
    return GradeResponse(score=score, total=total, recommended_level=level, summary=summary)

