"""First time onboarding: placement quiz generation and grading.

Quiz questions are generated by the configured LLM provider from the
track's topic list and what the learner says they already know. Grading
is deterministic and local so scores never depend on an LLM being
available. When no LLM key is configured the quiz endpoints return 503
and the frontend skips straight to the roadmap.
"""

import json
import re
from datetime import datetime, timezone

from fastapi import HTTPException
from pydantic import BaseModel, Field

from app import llm
from app.roadmap_store import RoadmapNotFound, list_roadmap_slugs, load_roadmap_topics

QUIZ_QUESTION_COUNT = 4


class GoalRequest(BaseModel):
    goal_text: str = Field(min_length=3, max_length=2000, description="Free text learning goal")


class GoalArea(BaseModel):
    name: str
    topics: list[str]


class GoalAnalysisResponse(BaseModel):
    track_slug: str
    summary: str
    areas: list[GoalArea]


class PlanRequest(BaseModel):
    slug: str
    goal_text: str = ""
    area_levels: dict[str, str] = Field(default_factory=dict)
    known_topics: list[str] = Field(default_factory=list)


class PlanPhase(BaseModel):
    name: str
    milestone: str
    topics: list[str]


class PlanResponse(BaseModel):
    slug: str
    summary: str
    phases: list[PlanPhase]


class QuizRequest(BaseModel):
    slug: str
    known_topics: list[str] = Field(default_factory=list)
    skill_level: str = "beginner"


class QuizQuestion(BaseModel):
    id: str
    question: str
    options: list[str]
    answer_index: int
    topic: str


class QuizResponse(BaseModel):
    slug: str
    questions: list[QuizQuestion]


class GradeRequest(BaseModel):
    questions: list[QuizQuestion]
    answers: list[int] = Field(description="Selected option index per question, -1 when skipped")


class GradeResponse(BaseModel):
    score: int
    total: int
    recommended_level: str
    summary: str


def _parse_json(raw: str) -> dict:
    """Parse an LLM JSON reply, tolerating prose or fences around the object."""
    cleaned = raw.strip()
    fence = re.match(r"^```(?:json)?\s*(.*?)\s*```$", cleaned, re.DOTALL)
    if fence:
        cleaned = fence.group(1).strip()
    try:
        data = json.loads(cleaned)
    except ValueError:
        start = cleaned.find("{")
        end = cleaned.rfind("}")
        if start == -1 or end <= start:
            raise HTTPException(status_code=502, detail="LLM reply contained no JSON object")
        try:
            data = json.loads(cleaned[start : end + 1])
        except ValueError as error:
            raise HTTPException(status_code=502, detail=f"LLM returned invalid JSON: {error}")
    if not isinstance(data, dict):
        raise HTTPException(status_code=502, detail="LLM returned unexpected JSON shape")
    return data


async def analyze_goal(payload: GoalRequest) -> GoalAnalysisResponse:
    """Parse a free text goal into a track and major skill areas."""
    if not llm.is_configured():
        raise HTTPException(status_code=503, detail="LLM is not configured on the server")

    slugs = list_roadmap_slugs()
    prompt = (
        "You are the Coursegram.ai onboarding assistant. A learner describes "
        "their goal in natural language. Pick the best matching track from the "
        "available tracks and identify the 3 to 6 major skill areas of that "
        "track the learner must master. Respond with JSON only: "
        '{"track_slug": "...", "summary": "one sentence confirming the goal", '
        '"areas": [{"name": "...", "topics": ["..."]}]} where area topics are '
        "short skill names, not full courses.\n"
        f"Available track slugs: {', '.join(slugs)}.\n"
        f"Learner goal: {payload.goal_text}"
    )
    raw = await llm.chat_completion(
        [{"role": "user", "content": prompt}],
        json_mode=True,
        temperature=0.2,
    )
    data = _parse_json(raw)
    track_slug = str(data.get("track_slug", "")).strip()
    if track_slug not in slugs:
        raise HTTPException(status_code=502, detail="The assistant could not match your goal to a track")
    areas = [
        GoalArea(name=str(item.get("name", "")).strip(), topics=[str(t) for t in item.get("topics", [])])
        for item in data.get("areas", [])
        if isinstance(item, dict) and item.get("name")
    ]
    if not areas:
        raise HTTPException(status_code=502, detail="The assistant could not identify skill areas")
    return GoalAnalysisResponse(
        track_slug=track_slug,
        summary=str(data.get("summary", "")).strip(),
        areas=areas,
    )


async def generate_plan(payload: PlanRequest) -> PlanResponse:
    """Generate a personalized roadmap from the track reference data."""
    if not llm.is_configured():
        raise HTTPException(status_code=503, detail="LLM is not configured on the server")

    try:
        topics = load_roadmap_topics(payload.slug)
    except RoadmapNotFound:
        raise HTTPException(status_code=404, detail="Unknown roadmap slug")

    known = set(topic.lower() for topic in payload.known_topics)
    remaining = [topic for topic in topics if topic.lower() not in known]
    levels = ", ".join(f"{area}: {level}" for area, level in payload.area_levels.items()) or "unknown"
    goal = payload.goal_text or f"master {payload.slug}"

    prompt = (
        "You are the Coursegram.ai path generator. Build a personalized "
        f"learning roadmap for a learner whose goal is: {goal}. "
        f"Track: {payload.slug}. Self rated proficiency per skill area: {levels}. "
        f"Topics the learner already knows (skip these): "
        f"{', '.join(payload.known_topics) if payload.known_topics else 'none'}.\n"
        "Use this ordered reference topic list from the track as the source of "
        "truth, taking topics verbatim where possible:\n"
        f"{'; '.join(remaining[:50])}\n\n"
        "Produce 3 to 5 sequential phases. Each phase has a short name, one "
        "concrete milestone the learner can demonstrate, and its topics taken "
        "from the reference list. If the learner rated an area intermediate or "
        "advanced, start that area at the next difficulty tier and include "
        "more advanced topics. Respond with JSON only: "
        '{"summary": "one sentence describing the path", "phases": '
        '[{"name": "...", "milestone": "...", "topics": ["..."]}]}'
    )
    raw = await llm.chat_completion(
        [{"role": "user", "content": prompt}],
        json_mode=True,
        temperature=0.3,
        max_tokens=3000,
    )
    data = _parse_json(raw)
    phases = [
        PlanPhase(
            name=str(item.get("name", "")).strip(),
            milestone=str(item.get("milestone", "")).strip(),
            topics=[str(topic) for topic in item.get("topics", []) if str(topic).strip()],
        )
        for item in data.get("phases", [])
        if isinstance(item, dict) and item.get("name")
    ]
    if not phases:
        raise HTTPException(status_code=502, detail="The assistant could not build a roadmap")
    return PlanResponse(
        slug=payload.slug,
        summary=str(data.get("summary", "")).strip(),
        phases=phases,
    )


async def generate_quiz(payload: QuizRequest) -> QuizResponse:
    """Ask the LLM for placement questions on the track's topics."""
    try:
        topics = load_roadmap_topics(payload.slug)
    except RoadmapNotFound:
        raise HTTPException(status_code=404, detail="Unknown roadmap slug")

    if not llm.is_configured():
        raise HTTPException(status_code=503, detail="LLM is not configured on the server")

    known = ", ".join(payload.known_topics) if payload.known_topics else "nothing yet"
    prompt = (
        "You build placement quizzes for software learners. "
        f"Track: {payload.slug}. Self reported level: {payload.skill_level}. "
        f"Topics the learner already knows: {known}. "
        "Create a multiple choice quiz that checks real understanding of the "
        "earliest and most fundamental topics of this track, weighted toward "
        "prerequisite knowledge. "
        f"Return exactly {QUIZ_QUESTION_COUNT} questions. "
        "Respond with JSON only using this shape: "
        '{"questions": [{"id": "q1", "question": "...", '
        '"options": ["...", "...", "...", "..."], "answer_index": 0, '
        '"topic": "..."}]}. '
        "Do not include any text outside the JSON."
    )
    raw = await llm.chat_completion(
        [{"role": "user", "content": prompt}],
        json_mode=True,
        temperature=0.6,
    )
    data = _parse_json(raw)
    questions = [QuizQuestion(**item) for item in data.get("questions", [])]
    if not questions:
        raise HTTPException(status_code=502, detail="Quiz generation returned no questions")
    return QuizResponse(slug=payload.slug, questions=questions[:QUIZ_QUESTION_COUNT])


def grade_quiz(payload: GradeRequest) -> GradeResponse:
    """Score the quiz locally and map the result to a skill level."""
    total = len(payload.questions)
    if total == 0 or len(payload.answers) != total:
        raise HTTPException(status_code=422, detail="Answers must match questions")

    score = 0
    missed: list[str] = []
    for question, answer in zip(payload.questions, payload.answers):
        if 0 <= answer == question.answer_index:
            score += 1
        else:
            missed.append(question.topic or question.id)

    ratio = score / total
    if ratio >= 0.8:
        level = "advanced"
    elif ratio >= 0.5:
        level = "intermediate"
    else:
        level = "beginner"

    if missed:
        summary = "Focus areas: " + ", ".join(sorted(set(missed))[:4]) + "."
    else:
        summary = "Strong across all quiz topics."
    return GradeResponse(score=score, total=total, recommended_level=level, summary=summary)

