"""First time onboarding: placement quiz generation and grading.

Quiz questions are generated by the configured LLM provider from the
track's topic list and what the learner says they already know. Grading
is deterministic and local so scores never depend on an LLM being
available. When no LLM key is configured the quiz endpoints return 503
and the frontend skips straight to the roadmap.
"""

import json
import re

from fastapi import HTTPException
from pydantic import BaseModel, Field

from app import llm
from app.roadmap_store import RoadmapNotFound, load_roadmap_topics

QUIZ_QUESTION_COUNT = 6


class QuizRequest(BaseModel):
    slug: str
    known_topics: list[str] = Field(default_factory=list)
    skill_level: str = "beginner"


class QuizQuestion(BaseModel):
    id: str
    question: str
    options: list[str]
    answer_index: int
    topic: str


class QuizResponse(BaseModel):
    slug: str
    questions: list[QuizQuestion]


class GradeRequest(BaseModel):
    questions: list[QuizQuestion]
    answers: list[int] = Field(description="Selected option index per question, -1 when skipped")


class GradeResponse(BaseModel):
    score: int
    total: int
    recommended_level: str
    summary: str


def generate_quiz(payload: QuizRequest) -> QuizResponse:
    """Ask the LLM for placement questions on the track's topics."""
    try:
        topics = load_roadmap_topics(payload.slug)
    except RoadmapNotFound:
        raise HTTPException(status_code=404, detail="Unknown roadmap slug")

    if not llm.is_configured():
        raise HTTPException(status_code=503, detail="LLM is not configured on the server")

    known = ", ".join(payload.known_topics) if payload.known_topics else "nothing yet"
    prompt = (
        "You build placement quizzes for software learners. "
        f"Track: {payload.slug}. Self reported level: {payload.skill_level}. "
        f"Topics the learner already knows: {known}. "
        "Create a multiple choice quiz that checks real understanding of the "
        "earliest and most fundamental topics of this track, weighted toward "
        "prerequisite knowledge. "
        f"Return exactly {QUIZ_QUESTION_COUNT} questions. "
        "Respond with JSON only using this shape: "
        '{"questions": [{"id": "q1", "question": "...", '
        '"options": ["...", "...", "...", "..."], "answer_index": 0, '
        '"topic": "..."}]}. '
        "Do not include any text outside the JSON."
    )
    raw = llm.chat_completion(
        [{"role": "user", "content": prompt}],
        json_mode=True,
        temperature=0.6,
    )
    try:
        data = json.loads(raw)
        questions = [QuizQuestion(**item) for item in data["questions"]]
    except (ValueError, KeyError, TypeError) as error:
        raise HTTPException(status_code=502, detail=f"Quiz generation failed: {error}")
    if not questions:
        raise HTTPException(status_code=502, detail="Quiz generation returned no questions")
    return QuizResponse(slug=payload.slug, questions=questions[:QUIZ_QUESTION_COUNT])


def grade_quiz(payload: GradeRequest) -> GradeResponse:
    """Score the quiz locally and map the result to a skill level."""
    total = len(payload.questions)
    if total == 0 or len(payload.answers) != total:
        raise HTTPException(status_code=422, detail="Answers must match questions")

    score = 0
    missed: list[str] = []
    for question, answer in zip(payload.questions, payload.answers):
        if 0 <= answer == question.answer_index:
            score += 1
        else:
            missed.append(question.topic or question.id)

    ratio = score / total
    if ratio >= 0.8:
        level = "advanced"
    elif ratio >= 0.5:
        level = "intermediate"
    else:
        level = "beginner"

    if missed:
        summary = "Focus areas: " + ", ".join(sorted(set(missed))[:4]) + "."
    else:
        summary = "Strong across all quiz topics."
    return GradeResponse(score=score, total=total, recommended_level=level, summary=summary)
