"""Per track project suggestions, generated by the LLM and cached on disk.

Projects are generated once per track from the skill graph and cached
under data/runtime/project_cache so the pipeline is stable, cheap, and
available when the LLM is not. Learner specific state (planned / in
progress / completed), evidence links, and AI analysis live in the
user_projects table.
"""

import json
import logging
import os
import re

from app import llm
from app.roadmap_store import RoadmapNotFound, load_roadmap_graph

logger = logging.getLogger("app.projects")

CACHE_DIR = os.path.join(os.path.dirname(__file__), "data", "runtime", "project_cache")

MAX_TOPICS_IN_PROMPT = 60


class ProjectError(Exception):
    pass


def _cache_path(slug: str) -> str:
    return os.path.join(CACHE_DIR, f"{slug}.json")


def _valid_projects(payload) -> list[dict] | None:
    if not isinstance(payload, dict):
        return None
    projects = payload.get("projects")
    if not isinstance(projects, list) or not projects:
        return None
    cleaned: list[dict] = []
    seen_titles: set[str] = set()
    for item in projects:
        if not isinstance(item, dict):
            continue
        title = str(item.get("title", "")).strip()
        description = str(item.get("description", "")).strip()
        stage = str(item.get("stage", "")).strip()
        difficulty = str(item.get("difficulty", "intermediate")).strip().lower()
        skills = [str(s).strip() for s in item.get("skills", []) if str(s).strip()]
        related = [str(t).strip() for t in item.get("related_topics", []) if str(t).strip()]
        if not title or title.lower() in seen_titles or not description:
            continue
        seen_titles.add(title.lower())
        if difficulty not in ("beginner", "intermediate", "advanced"):
            difficulty = "intermediate"
        cleaned.append(
            {
                "title": title,
                "description": description,
                "stage": stage,
                "difficulty": difficulty,
                "skills": skills[:6],
                "related_topics": related[:6],
            }
        )
    if len(cleaned) < 3:
        return None
    return cleaned


def _load_cache(slug: str) -> list[dict] | None:
    try:
        with open(_cache_path(slug), encoding="utf-8") as handle:
            payload = json.load(handle)
    except (OSError, json.JSONDecodeError):
        return None
    return _valid_projects(payload)


def _save_cache(slug: str, projects: list[dict]) -> None:
    os.makedirs(CACHE_DIR, exist_ok=True)
    payload = {"slug": slug, "generated_at": datetime_now_iso(), "projects": projects}
    with open(_cache_path(slug), "w", encoding="utf-8") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2)


def datetime_now_iso() -> str:
    import datetime

    return datetime.datetime.now(datetime.timezone.utc).isoformat()


def _project_prompt(graph: dict) -> str:
    nodes = graph.get("nodes", [])
    domains = graph.get("domains", ["core"])
    topics = [str(node["name"]) for node in nodes][:MAX_TOPICS_IN_PROMPT]
    choice_groups = graph.get("choice_groups", [])
    group_hint = ""
    if choice_groups:
        group_names = [str(grp.get("prompt", "")) for grp in choice_groups]
        group_hint = (
            "This track contains choice groups (" + "; ".join(group_names) + "). "
            "Where a project depends on one, scope it to any single option and say so.\n"
        )
    return (
        "You design applied learning projects for Coursegram, an AI learning "
        "path product. For the track below, design 6 portfolio worthy projects "
        "that a learner builds to prove the track's skills. Spread them across "
        "difficulty (at least 2 beginner, at least 1 advanced) and across the "
        "track's stages.\n"
        f"Track: {graph.get('slug', '')} ({graph.get('title', '')}). "
        f"Stages/domains: {', '.join(domains)}.\n"
        "Reference topics (assign related_topics verbatim from this list):\n"
        f"{'; '.join(topics)}\n"
        + group_hint
        + "Respond with JSON only: {\"projects\": [{\"title\": \"...\", "
        "\"description\": \"2 to 3 sentences: what the learner builds and why "
        "it proves the skills\", \"stage\": \"one of the listed stages\", "
        "\"difficulty\": \"beginner|intermediate|advanced\", \"skills\": "
        "[\"...\"], \"related_topics\": [\"verbatim topic names\"]}]}"
    )


async def get_track_projects(slug: str) -> list[dict]:
    """Return the track's project suggestions, generating and caching once."""
    try:
        graph = load_roadmap_graph(slug)
    except RoadmapNotFound:
        raise RoadmapNotFound(slug)

    cached = _load_cache(slug)
    if cached is not None:
        return _with_ids(slug, cached)

    if not llm.is_configured():
        raise llm.LLMNotConfigured("Set NVIDIA_API_KEY to enable project generation")

    raw = await llm.chat_completion(
        [{"role": "user", "content": _project_prompt(graph)}],
        json_mode=True,
        temperature=0.4,
        max_tokens=3000,
    )
    try:
        data = json.loads(_extract_json(raw))
    except (json.JSONDecodeError, ValueError) as error:
        logger.warning("Project generation parse failed for %s: %s", slug, error)
        raise ProjectError("Could not parse generated projects") from error
    projects = _valid_projects(data)
    if projects is None:
        logger.warning("Project generation returned unusable projects for %s", slug)
        raise ProjectError("Generated projects were unusable")
    _save_cache(slug, projects)
    return _with_ids(slug, projects)


def _extract_json(raw: str) -> str:
    cleaned = raw.strip()
    fence = re.match(r"^```(?:json)?\s*(.*?)\s*```$", cleaned, re.DOTALL)
    if fence:
        cleaned = fence.group(1).strip()
    start = cleaned.find("{")
    end = cleaned.rfind("}")
    if start != -1 and end > start:
        cleaned = cleaned[start : end + 1]
    return cleaned


def _with_ids(slug: str, projects: list[dict]) -> list[dict]:
    out = []
    for index, project in enumerate(projects, start=1):
        item = dict(project)
        item["id"] = f"{slug}-p{index}"
        out.append(item)
    return out


def load_cached_projects(slug: str) -> list[dict] | None:
    """Return cached projects without generating, or None when absent."""
    cached = _load_cache(slug)
    if cached is None:
        return None
    return _with_ids(slug, cached)


async def generate_custom_project(profile, slug: str, hint: str | None = None) -> dict:
    """Generate one ad hoc project for the learner's track on request."""
    try:
        graph = load_roadmap_graph(slug)
    except RoadmapNotFound:
        raise RoadmapNotFound(slug)
    if not llm.is_configured():
        raise llm.LLMNotConfigured("Set NVIDIA_API_KEY to enable project generation")

    topics = [str(node["name"]) for node in graph.get("nodes", [])][:MAX_TOPICS_IN_PROMPT]
    stage_hint = f"The learner asked for this focus: {hint}. " if hint else ""
    prompt = (
        "You design applied learning projects for Coursegram. Design ONE "
        f"portfolio worthy project for the track {slug} "
        f"({graph.get('title', '')}) at the learner's level "
        f"({profile.skill_level}). {stage_hint}"
        "Reference topics (assign related_topics verbatim from this list):\n"
        f"{'; '.join(topics)}\n"
        "Respond with JSON only: {\"title\": \"...\", \"description\": "
        "\"2 to 3 sentences: what the learner builds and why it proves the "
        "skills\", \"stage\": \"one stage of the track\", \"difficulty\": "
        "\"beginner|intermediate|advanced\", \"skills\": [\"...\"], "
        "\"related_topics\": [\"verbatim topic names\"]}"
    )
    raw = await llm.chat_completion(
        [{"role": "user", "content": prompt}],
        json_mode=True,
        temperature=0.5,
        max_tokens=1200,
    )
    try:
        data = json.loads(_extract_json(raw))
    except (json.JSONDecodeError, ValueError) as error:
        logger.warning("Custom project parse failed for %s: %s", slug, error)
        raise ProjectError("Could not parse the generated project") from error
    single = _valid_projects({"projects": [data] if isinstance(data, dict) else []})
    if single is None:
        raise ProjectError("The generated project was unusable")
    return single[0]


async def analyze_project(profile, definition: dict, row: dict) -> dict:
    """Review the learner's project evidence and return honest feedback."""
    if not llm.is_configured():
        raise llm.LLMNotConfigured("Set NVIDIA_API_KEY to enable project analysis")

    repo = row.get("repo_url") or "not provided"
    demo = row.get("demo_url") or "not provided"
    prompt = (
        "You are a senior engineer reviewing a learner's project submission "
        "for Coursegram, an AI learning path product. Be honest and specific: "
        "acknowledge real strengths, point out real gaps, and never inflate "
        "the assessment. If no evidence links were provided, say the work "
        "cannot be fully verified and focus on concrete next steps.\n"
        f"Project: {definition['title']}. {definition['description']}\n"
        f"Expected skills: {', '.join(definition.get('skills', [])) or 'not listed'}.\n"
        f"Learner level: {profile.skill_level}. Track: {row.get('slug', '')}.\n"
        f"Project state: {row.get('state', 'planned')}.\n"
        f"Repository link: {repo}\n"
        f"Live demo link: {demo}\n"
        "Respond with JSON only: {\"verdict\": \"2 to 3 honest sentences about "
        "the submission relative to the project goal\", \"strengths\": "
        "[\"...\"], \"gaps\": [\"...\"], \"next_steps\": [\"...\"]} with 2 to 4 "
        "items in each list."
    )
    raw = await llm.chat_completion(
        [{"role": "user", "content": prompt}],
        json_mode=True,
        temperature=0.3,
        max_tokens=1500,
    )
    try:
        data = json.loads(_extract_json(raw))
    except (json.JSONDecodeError, ValueError) as error:
        logger.warning("Project analysis parse failed: %s", error)
        raise ProjectError("Could not parse the project analysis") from error
    if not isinstance(data, dict):
        raise ProjectError("Unexpected analysis shape")
    analysis = {
        "verdict": str(data.get("verdict", "")).strip(),
        "strengths": [str(item).strip() for item in data.get("strengths", []) if str(item).strip()][:4],
        "gaps": [str(item).strip() for item in data.get("gaps", []) if str(item).strip()][:4],
        "next_steps": [str(item).strip() for item in data.get("next_steps", []) if str(item).strip()][:4],
        "analyzed_at": datetime_now_iso(),
    }
    if not analysis["verdict"]:
        raise ProjectError("The analysis returned no verdict")
    return analysis
